site_name: Candy Mkdocs Theme

dev_addr: 127.0.0.1:8225

theme:
  name: null
  custom_dir: 'candy_theme/'

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition

repo_url: https://github.com/usecandy/candy-mkdocs-theme
